You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

In [21]:
def rotate_matrix(df):
    
    rotation_matrix = np.zeros((df.shape[1], df.shape[0]))
    
    for i in range(df.shape[0]):
        
        j = df.shape[1] - i - 1
        
        rotation_matrix[i, j] = 1
        
    return np.matmul(df.T,rotation_matrix)

In [22]:
a = np.matrix('1 2; 3 4')
print(a)
print(rotate_matrix(a))

[[1 2]
 [3 4]]
[[3. 1.]
 [4. 2.]]


In [19]:
b = np.matrix('5 1 9 11; 2 4 8 10; ')

0 1
[[0. 1.]
 [0. 0.]]
1 0
[[0. 1.]
 [1. 0.]]


matrix([[3., 1.],
        [4., 2.]])